/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.util.Arrays;
import java.util.Iterator;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import logica.Fabrica;
import logica.Interfaces.IControladorUsuario;
import logica.Interfaces.IPropCat;
import logica.Clases.DtUsuario;

/**
 *
 * @author Martin
 */
public class AltaPropuesta1 extends javax.swing.JInternalFrame {

    private IControladorUsuario ICU;
    private IPropCat ICP;
    private String nickProp;
    private String Categoria;
    
    

    public AltaPropuesta1() {
        initComponents();
        this.ICU = Fabrica.getInstance().getIControladorUsuario();
        this.ICP = Fabrica.getInstance().getControladorPropCat();

        List listCat = ICP.ListarCategorias();
        Iterator it = listCat.iterator();

        while (it.hasNext()) {
            jComboBoxCategoria.addItem(it.next().toString());
        }

        List<DtUsuario> listUsu = ICU.ListarProponentes2();
        DefaultTableModel modelo = (DefaultTableModel) jTableAltaProp1.getModel();

        modelo.setRowCount(0);

        for (int i = 0; i < listUsu.size(); i++) {
            DtUsuario usu = (DtUsuario) listUsu.get(i);
            Object[] datos = {usu.getNickName(), usu.getNombre(), usu.getApellido(), usu.getCorreo()};

            modelo.addRow(datos);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAlProp1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAltaProp1 = new javax.swing.JTable();
        jButtonCrearPropuesta = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNickName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jTableAltaProp1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NickName", "Nombre", "Apellido", "Correo"
            }
        ));
        jTableAltaProp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAltaProp1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAltaProp1);

        jButtonCrearPropuesta.setText("CrearPropuesta");
        jButtonCrearPropuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearPropuestaActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Categoria:");

        jLabel2.setText("Nickname del proponente a seleccionar:");

        javax.swing.GroupLayout jPanelAlProp1Layout = new javax.swing.GroupLayout(jPanelAlProp1);
        jPanelAlProp1.setLayout(jPanelAlProp1Layout);
        jPanelAlProp1Layout.setHorizontalGroup(
            jPanelAlProp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlProp1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelAlProp1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelAlProp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGroup(jPanelAlProp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAlProp1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCrearPropuesta)
                        .addGap(41, 41, 41)
                        .addComponent(jButtonCancelar)
                        .addGap(36, 36, 36))
                    .addGroup(jPanelAlProp1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAlProp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNickName, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelAlProp1Layout.setVerticalGroup(
            jPanelAlProp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlProp1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelAlProp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNickName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanelAlProp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanelAlProp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCrearPropuesta)
                    .addComponent(jButtonCancelar))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelAlProp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelAlProp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearPropuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearPropuestaActionPerformed
        // TODO add your handling code here:

        this.Categoria = Arrays.toString(jComboBoxCategoria.getSelectedObjects());

        if ( !jTextFieldNickName.getText().isEmpty() && this.Categoria != null) {

            if (ICP.seleccionarUC(jTextFieldNickName.getText(), this.Categoria)) {

                AltaPropuesta2 altProp2 = new AltaPropuesta2(jTextFieldNickName.getText(), this.Categoria);
                inicio.Escritorio.add(altProp2);
                this.setVisible(false);
                altProp2.toFront();
                altProp2.setVisible(true);
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "El nickName ingresado es incorrecto");
                jTextFieldNickName.setText("");
            }

        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Debe completar los campos para continuar");
        }

    }//GEN-LAST:event_jButtonCrearPropuestaActionPerformed

    private void jTableAltaProp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAltaProp1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableAltaProp1MouseClicked

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCrearPropuesta;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelAlProp1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAltaProp1;
    private javax.swing.JTextField jTextFieldNickName;
    // End of variables declaration//GEN-END:variables
}
